### ISSUE TITLE
The sum of the values ​​of the columns are not correct

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#1]
The sum of the values ​​of the columns are not correct.

![image](https://user-images.githubusercontent.com/42243532/45514487-da87e680-b77b-11e8-8240-5e9a6a46f928.png)

**Comment by Arthur-Milchior** [comment]
I assume that there are no subdecks of 1 - QC, apparts from the one you show. 
61+8+22+3+5=99, so I guess that the problem you are talking about is that the «Due today (all)» column show 109 on the line «1 - QC»
Are you sure that there are no cards belonging to «1 - QC» and not to its subdeck ? That may explain the difference if they are 10 due cards which are due and not in the subdecks.

Otherwise, if its ok with you, can you share your deck, so I can investigate myself ?

**Comment by cjdduarte** [comment]
I simplified the deck for ease. I believe error is in the column (Learning
Now (later). It should appear there *165*, correct? Below is an addon that
I have with the correct numbers. see that *226 *is right. but not sum.

[image: image.png]


Sds,
Carlos jackson


Em qui, 13 de set de 2018 às 17:49, Arthur Milchior <
notifications@github.com> escreveu:

**Comment by Arthur-Milchior** [comment]
I don't understand where the numbers 165 and 226 come from. Note furthermore that on github, I see no attached image, thus I can't see your example.

Could you share the deck ? I believe it'll be easier

Regards
Arthur

**Comment by cjdduarte** [comment]
in the image, the filter representing the number 165 (is:learn).
226 is the total due that I have to study today.

follow the deck

[image: image.png]

[image: image.png]
Sds,
Carlos jackson


Em qui, 13 de set de 2018 às 18:48, Arthur Milchior <
notifications@github.com> escreveu:

**Comment by Arthur-Milchior** [comment]
Sorry, but I didn't receive the deck nor any image. What means "follow the
deck" ?

Do you mean that, in the browser, when you search for is:learn, you see 165
cards ? And when you search for is:due you see 226 cards ?

Are you on anki 2.0 or 2.1 ?

Le ven. 14 sept. 2018 à 00:04, cjdduarte <notifications@github.com> a
écrit :

**Comment by cjdduarte** [comment]
Sorry My English.  follow the deck  = attachment

Do you mean that, in the browser, when you search for is:learn, you see 165
cards ? *YES*
And when you search for is:due you see 226 cards ?  *YES*


https://drive.google.com/file/d/1R-8RKOLlJxQ728ZsaoromQ-qB2X7hitV/view?usp=sharing

Sds,
Carlos jackson


Em qui, 13 de set de 2018 às 19:26, Arthur Milchior <
notifications@github.com> escreveu:

**Comment by cjdduarte** [comment]
As I consider what values your columns should be showing:

1) Learning now: *165 *- ERROR
2) Due today: 61 - OK
3) New: 0 and unssen (40) - OK
4) Buried: 0 - OK
5) Total card / Note: 437/437 - OK
6) Today: 226 - OK
7) Market: 5 - OK

Sds,
Carlos jackson


Em qui, 13 de set de 2018 às 19:33, Carlos Duarte <cjdduarte@gmail.com>
escreveu:

**Comment by Arthur-Milchior** [comment]
Thank you for signaling the bug. I'll try to understand it later. I'll let you know when it's corrected.

**Comment by cjdduarte** [comment]
Tanks.

Sds,
Carlos jackson


Em qui, 13 de set de 2018 às 21:09, Arthur Milchior <
notifications@github.com> escreveu:

**Comment by Arthur-Milchior** [comment]
Please, update your add-on from anki's website. It should be corrected now.

Let me now in case there is another trouble.

Learning now has three numbers. Learning cards now, learning cards later 
today, and learning cards you'll see another day.

The problem was that I never use learning cards with a distance of more 
than a day, so I never noticed the trouble you noticed.


Arthur

**Comment by cjdduarte** [comment]
Got it. Now it's OK. Thank you.

Other questions:

1) Is it correct to see these messages?

[image: image.png]

2) Is it a detail only, but can not standardize this icon?

Original:

[image: image.png]


With your addon:

[image: image.png]

Sds,
Carlos jackson


Em sex, 14 de set de 2018 às 12:14, Arthur Milchior <
notifications@github.com> escreveu:

**Comment by Arthur-Milchior** [comment]
I don't know what you do with images, but i can not see any of the image in your answer. Thus I have no way to answer you, since I don't know what the problem is

**Comment by cjdduarte** [comment]
sending in pdf

Sds,
Carlos jackson


Em sex, 14 de set de 2018 às 13:31, Arthur Milchior <
notifications@github.com> escreveu:

**Comment by Arthur-Milchior** [comment]
No pdf received yet. 
Out of curiosity, do you answer by email, or by github directly ? I guess answering by email may be the problem

**Comment by cjdduarte** [comment]
Excuse me. Now I'm in github. I was responding by email.
see if you can now open the pdf

[Gmail.pdf](https://github.com/Arthur-Milchior/anki-enhance-main-window/files/2384196/Gmail.pdf)

**Comment by Arthur-Milchior** [comment]
No trouble.


I corrected the tooltip on the left. However, I can't figure out how to 
correct the image on the right, and I must admit I am not interested 
enough to actually check how to really correct it.


Thank you for letting me know for the bugs. If you find other bugs, 
please let me know


Regards

Arthur

**Comment by cjdduarte** [comment]
I await a new publication. Thank you

**Comment by cjdduarte** [comment]
I enabled the "young" and "mature" columns and they are with several decimal places. How to correct?
![casas decimais](https://user-images.githubusercontent.com/42243532/45580690-7c85fc80-b86a-11e8-8477-7da91c7cfa18.jpg)
Sorry, I really like this add-on.

**Comment by cjdduarte** [comment]
I found the error.
I fix:

`column:conditionString(self.count["absolute"][kind][column],str(round(100*self.count["absolute"][kind][column]/self.count["absolute"][kind]["total"],1))+ "%") if self.count["absolute"][kind]["total"] else ""`

I took the liberty and made minor corrections to your code. And I found some bugs. I would like to share with you.

I do not know if you will see the modifications I made, but I would like to congratulate you again for this addon. I really like it and I'll use it for this custom version.

**
[enhancedMain.zip](https://github.com/Arthur-Milchior/anki-enhance-main-window/files/2385717/enhancedMain.zip)

**


**Congratulations again.**

**Comment by cjdduarte** [comment]
I saw that you fixed the problem differently. I will report the other issues I encountered in new topics. You can close this topic.
