### ISSUE TITLE
Question: What is the difference between ("learning later") and ("undue")?

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#13]
I was validating the aggregation of the columns of my decks in this format below and I would like to know the conceptual difference of these two columns ("learning later") and ("undue")?

The total gives: 1773 + 48 + 114 + 334 = 2.269

But I did not understand the explanation in the source code for:
("learning later") = 114
("undue") = 334

![image](https://user-images.githubusercontent.com/42243532/46383269-e9303200-c685-11e8-84bd-a9f76cf11747.png)

**Comment by Arthur-Milchior** [comment]
Learning corresponds to cards in learning. Later mean you only consider
cards for which there is still a delay
Undue is the sum of young and mature

**Comment by cjdduarte** [comment]
OK. Tanks.
