### ISSUE TITLE
Can't delete Total note column

### ISSUE THREAD

**Issue by Villiam909** [Arthur-Milchior/anki-enhance-main-window#14]
Hi!

Love the add-on, it is really good! 

I have one issue: I want to delete the column "Total note", with both card and note value count, and instead use the Card only column "Total". When I put a # in front of "Total note" and restart Anki the add-on crashes and doesn't open. All other columns can be disabled/enabled/moved without problems, it is only disabling of the "Total note"-column that causes the crashes. 

Is there a way around this?

**Comment by Arthur-Milchior** [comment]
@Villiam909 Can you please confirm that the bug is solved, please ?

**Comment by Villiam909** [comment]
Now working, nice! But noticed that the same thing now happens when deactivating "Unseen new" (the add-on cannot load if it is deactivated).

**Comment by Villiam909** [comment]
Fixed. Same problem now when activating "New" (New today).

**Comment by Villiam909** [comment]
This is the message that appears:

When loading 'Enhance main window':
Traceback (most recent call last):
  File "aqt/addons.py", line 60, in loadAddons
  File "/Users/villiamvejbrinkkildal/Library/Application Support/Anki2/addons21/877182321/__init__.py", line 1, in <module>
    from . import enhancedMain
  File "/Users/villiamvejbrinkkildal/Library/Application Support/Anki2/addons21/877182321/enhancedMain.py", line 79
    (("new"), _("New")+"<br/>"+_("today") ,"blue", _("Unseen")+ _("cards")+ _("you will see today")+"<br/>"+_("(what anki calls )+_("new cards"), "absolute", "subdeck"),
                                                                                                                                       ^
SyntaxError: invalid syntax

**Comment by Arthur-Milchior** [comment]
Corrected

**Comment by Villiam909** [comment]
Working!
