### ISSUE TITLE
code corrections

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#2]
1) There is no gears class in your code:

![image](https://user-images.githubusercontent.com/42243532/45587120-90b41300-b8d7-11e8-99e8-2366ddbbe66d.png)

2) I created the class below so that an arrow appears when hovering over the names of the deck.

![image](https://user-images.githubusercontent.com/42243532/45587123-9f9ac580-b8d7-11e8-9df8-bc48327ff0e2.png)
And I inserted the tooltip class here
![image](https://user-images.githubusercontent.com/42243532/45587140-f2747d00-b8d7-11e8-8c8d-f3951ee7268b.png)

3) I removed this arrow to make it look more like the original layout

![image](https://user-images.githubusercontent.com/42243532/45587147-2059c180-b8d8-11e8-9aaf-42dd36d23696.png)

![image](https://user-images.githubusercontent.com/42243532/45587153-56974100-b8d8-11e8-9a3e-b7f65da04b92.png)

**Comment by Arthur-Milchior** [comment]
Would you mind doing a pull request with your change ? I best that - for me - it would be the easiest way to actually use your gears.

**Comment by cjdduarte** [comment]
OK.

**Comment by cjdduarte** [comment]
I'll still do that.
I saw that you created the file html.py
I've made the changes in these 2 files.

**Comment by cjdduarte** [comment]
The corrections you made are sufficient
