### ISSUE TITLE
Bug: Unresponsive, Crash

### ISSUE THREAD

**Issue by sandersantema** [Arthur-Milchior/anki-enhance-main-window#21]
1. Doing just normal Anki stuff
2. Clicking on decks doesn't open them
3. Anki freezes and takes up cpu. 

Happens quite a lot, maybe it has something to do with the refresh of the main window? Because it seems to be periodic.

I believe this plugin is causing it since it happens on the homescreen and it's one of the plugins which I've updated today (yesterday I updated my plugins to and didn't have any problems). But it might be something else. 

The crashlog from the system itself (macOS), Anki doesn't generate/ show a crashlog:
https://pastebin.com/WDM7j1WG

Here is my plugin list:
![schermafbeelding 2018-11-27 om 20 20 00](https://user-images.githubusercontent.com/21057514/49105812-ddc24700-f281-11e8-97d3-4ead83b4d88b.png)

Anki Taking up CPU:
![schermafbeelding 2018-11-27 om 20 11 13](https://user-images.githubusercontent.com/21057514/49105809-ddc24700-f281-11e8-9542-9b6903ff978f.png)

**Comment by Arthur-Milchior** [comment]
I undid the last change. Is it better when you update ?

**Comment by Arthur-Milchior** [comment]
I don't know what to do with the content of the link you provided.

**Comment by sandersantema** [comment]
> I undid the last change. Is it better when you update ?

Hi, I see you updated the github repo but I believe you haven't updated Ankiweb yet.

**Comment by sandersantema** [comment]
> I don't know what to do with the content of the link you provided.

Yea it's quite cryptic, it's the crashreport which macOS generates. I think there's a lot of information about the crash in the file so I thought I'd post it here for completeness sake.

**Comment by Arthur-Milchior** [comment]
I didn't think about asking. Can you tell me which version of anki you have ? Which os ? Everything from the about window in fact

**Comment by Arthur-Milchior** [comment]
By the way, I thank you for the crash report. I just meant that I fear I have no way to use this one in particular, I don't know how to read it. It does not seems to state any particular error in anki's code, which is the only thing I could use

**Comment by Arthur-Milchior** [comment]
Great, if everything is fixed, I can close the report.
You are welcome for the fix. I have been working on anki's add-on for two weeks, so it's quite easy to fix things quickly since the code is already open and I the code is already loaded in my head.

**Comment by Arthur-Milchior** [comment]
Great, if everything is fixed, I can close the report.
You are welcome for the fix. I have been working on anki's add-on for two weeks, so it's quite easy to fix things quickly since the code is already open and I the code is already loaded in my head.
