### ISSUE TITLE
"color empty" dont work

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#25]
The parameter: "color empty": "red" is not working in this new version.

**Comment by Arthur-Milchior** [comment]
Its supposed to work. I can't promise nothing else break. The code was changed a lot. Hopefully, it will be cleaner, easier to read, and to maintain.

May i ask you to download and test the code before I upload it on anki's server, please ?
On my computer it seems to work. At least as much as it did worked before. It's probable that everything is not repaired yet

**Comment by cjdduarte** [comment]
Thank you. In the github version it is working
