### ISSUE TITLE
Possible to combine Burried/Suspended Columns?

### ISSUE THREAD

**Issue by alaskakw** [Arthur-Milchior/anki-enhance-main-window#27]
Is it possible to combine the Buried and Suspended columns similar to how there's a new(unseen) column?

**Comment by Arthur-Milchior** [comment]
I am thinking about a way to allow to combine arbitrary columns. It won't be before a few weeks, in the best case.
I'm spending all of my free time on another huge add-on right now.

**Comment by alaskakw** [comment]
Thanks for the update!   
  
  
  

  
  

  
  
>

**Comment by Arthur-Milchior** [comment]
It seems to already be present in the current version on github. So I'm not sure to understand your request.
Unless you mean that you want parenthesis instead of a slash. In which case I must admit I'm slightly too lazy to add this option for purely aesthetical purpose
