### ISSUE TITLE
This new version of github is crashing

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#30]
This new version of github is crashing.

When trying to open the level of a subdeck the screen hangs and I can not close the Anki leaving the screen blank.

![image](https://user-images.githubusercontent.com/42243532/51437711-ec791900-1c88-11e9-9393-78e96005bc21.png)

**Comment by Arthur-Milchior** [comment]
A big correction was done less than a minute ago

**Comment by Arthur-Milchior** [comment]
Honestly, I'm even amazed that the version kind of worked on your computer. I was not even able to open my real collection with the bug I had

**Comment by cjdduarte** [comment]
Tanks
