### ISSUE TITLE
Error adding column 2

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#32]
The "unseen later" column generates an error in the addon when inserting it

**Comment by Arthur-Milchior** [comment]
Without error message, I'm not sure exactly what's the error.
Note that this column is not in the config.json, so it's not a column that anyone were supposed to use

**Comment by cjdduarte** [comment]
I understood, I saw that this column is new and I found it interesting to put it instead of "unsee"

![image](https://user-images.githubusercontent.com/42243532/51443561-bca23380-1cd1-11e9-840c-b1dbcff2951c.png)

**Comment by cjdduarte** [comment]
`Erro 
Ocorreu um erro. Por favor, inicialize Anki enquanto segura a tecla SHIFT, isto vai desabilitar temporariamente os complementos (add-ons) que você instalou. 
Se o problema ocorre somente quando os complementos estão habilitados, por favor vá para Ferramentas > Complementos e desabilite algum(s) complemento(s), para descobrir qual complemento é o responsável pelo problema. 
Assim que você descobrir o complemento responsável, por favor relate o problema na seção de complementos em nossa página de ajuda. 
Informação de Debug:
Anki 2.1.8 (71e0c880) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
  File "aqt\webview.py", line 300, in handler
  File "aqt\deckbrowser.py", line 90, in __renderPage
  File "D:\Anki\ankidata21\addons21\z_enhancedMain\node.py", line 572, in renderDeckTree
    buf += self._deckRow(node, depth, len(nodes))
  File "D:\Anki\ankidata21\addons21\z_enhancedMain\changeFunction.py", line 35, in deckRow
    return node.htmlRow(self,depth,cnt)
  File "D:\Anki\ankidata21\addons21\z_enhancedMain\node.py", line 533, in htmlRow
    end_line +
  File "D:\Anki\ankidata21\addons21\z_enhancedMain\node.py", line 513, in getNumberColumns
    buf += number_cell(conf.get("color","black"), contents, getOverlay(conf))
  File "D:\Anki\ankidata21\addons21\z_enhancedMain\strings.py", line 70, in getOverlay
    return defaultOverlay[conf["name"]]
<class 'KeyError'>: 'unseen later'`

**Comment by Arthur-Milchior** [comment]
Is the error still present ?

**Comment by cjdduarte** [comment]
Now it's working.
