### ISSUE TITLE
refresh rate is not working

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#33]
In this new version of github, the refresh rate is not working.

![example](https://user-images.githubusercontent.com/42243532/51443526-30900c00-1cd1-11e9-8426-f0a083b5e387.gif)

**Comment by Arthur-Milchior** [comment]
Well seen.

I don't know how to use it correctly right now. May be I'll add it again later. But right now at least, the documentation is consistent with the features

**Comment by cjdduarte** [comment]
OK, is that in the officially published versions always worked. In this new version that has stopped working.

**Comment by cjdduarte** [comment]
If you can look at this.
I have to leave Anki at all times to see the changes made.

**Comment by Arthur-Milchior** [comment]
With the last version you still have the problem ?
Currently, it is refreshed as often as standard anki.

**Comment by cjdduarte** [comment]
Now it's working. Thank you.
