### ISSUE TITLE
enhance-main-window Anki 2.1.8

### ISSUE THREAD

**Issue by dedu6ka** [Arthur-Milchior/anki-enhance-main-window#35]
1. The column "Learning" disappeared  but the Red cards do show-up correctly in column 
"Today". ( updated my copy Today).

2. Please move column "Today" all the way to the left - to be the 1st column. 

Thank you.

**Comment by Arthur-Milchior** [comment]
You can move column yourself. In the configuration file, you just have to reorder the «today» column to be the first column of the list

**Comment by Arthur-Milchior** [comment]
Similarly, I just checked, you can decide to show the column «learning». It still works. You just have to set «present» to «true» in the configuration, in the dictionary related to «learning»

**Comment by dedu6ka** [comment]
From the user's perspective, these two columns are the most important.
They should be visible right from the start. 
PS. 
I am surprised - considering how many details you put in the Description to make sure that we get it - that you want the user to edit the addon in order to see the vital info.  
Hoping that you reconsider your decision.  
Thank you.

**Comment by dedu6ka** [comment]
In the version 2.0
i noticed that in column "Learn Later", the number of cards 'in-waiting' disappeares too soon; i hve set the timer on 10m, came back to check and the "Nomber" was gone.  
I think it should stay there till 4am.

**Comment by Arthur-Milchior** [comment]
I am sorry, but I do not maintain version 2.0 anymore.
