### ISSUE TITLE
negative count

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#40]
since this last update, began to appear negative numbers in the return count of some cards (column: "learning now").

![screenshot_1](https://user-images.githubusercontent.com/42243532/52561543-d4f20380-2de2-11e9-97c3-880757489e1b.png)

**Comment by cjdduarte** [comment]
Apparently when I close the Anki and return, the information is correct. But I'm forced to close it.

**Comment by Arthur-Milchior** [comment]
Let me know if you have the bug again. I don't know what caused this.

Le lun. 11 févr. 2019 à 13:05, Carlos Duarte <notifications@github.com> a
écrit :

**Comment by cjdduarte** [comment]
Just try again or download some version (github?) Other than official?

**Comment by cjdduarte** [comment]
I tested here again and the problem continues. The negative number appears and if you close the Anki and return, the information becomes correct. I use this setting.
Until yesterday it worked perfectly.

![image](https://user-images.githubusercontent.com/42243532/52562699-7f1f5a80-2de6-11e9-8505-17c19bd33c07.png)

**Comment by cjdduarte** [comment]
Did you even evaluate this? Still occurs. this was today

![image](https://user-images.githubusercontent.com/42243532/52710316-2e3e6c00-2f76-11e9-80c7-d8e44e92d050.png)

**Comment by Arthur-Milchior** [comment]
Can you share your collection or tell me how to reproduce it from a new collection ? because I can't reproduce this

**Comment by cjdduarte** [comment]
I will try to separate some data here to make sure that you can reproduce the error.

**This error occurs only in this field. Do you keep it enabled?**


```
  {
            "absolute": true,
            "color": "green",
            "description": "Cartões em aprendizagem para hoje <br/> ou o tempo em minutos para retorno",
            "header": "AprHoje",
            "name": "learning now",
            "overlay": "Cartões em aprendizagem para hoje <br/> ou o tempo em minutos para retorno",
            "percent": false,
            "present": true,
            "subdeck": true
        }
```

**Comment by Arthur-Milchior** [comment]
I added «learning now».
But actually, I used «learning all» which contains the content of «learning now»

**Comment by cjdduarte** [comment]
I use separate as I leave on the left side all the columns due for today and the columns on the right everything that will come tomorrow or later.

I inserted your "learning all" column next to the "learning now" for tests and I exported a database. I will simulate my study here today.

**Comment by cjdduarte** [comment]
Since the last update of the addon, the problem has not occurred any more.
I'll close this topic. Thanks for listening.

**Comment by Arthur-Milchior** [comment]
You are the second person telling me that a bug disappear while I did nothing to correct it. That beging to seem really strange.

Well, I'm happy for you that everything works well.
