### ISSUE TITLE
column: "reviewed today / repeated today"

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#43]
In this new version, there is some wrong sum.
I have not studied any cards today yet. So this column should be empty. Look.

**Old Version (Correct)**

![image](https://user-images.githubusercontent.com/42243532/52621185-d1678680-2e8d-11e9-8f60-e842c680072b.png)

**New Version (Today)**

![image](https://user-images.githubusercontent.com/42243532/52621276-02e05200-2e8e-11e9-8c81-784bfddff3e0.png)

**Comment by Arthur-Milchior** [comment]
Did you change the hour at which the day start ? I assume no, but I may be part of the problem.
More realistically, can you give me the list of add-ons you have ? The simplest explanation would be that an add-on change the scheduling option. 
I count cards seen today by doing "next due date-interval". But if some add-on change the due date, then this count become false

**Comment by Arthur-Milchior** [comment]
The wrong numbers are really close of "AprHoje". Can you tell me what AprHoje means ?

**Comment by cjdduarte** [comment]
> Did you change the hour at which the day start ? I assume no, but I may be part of the problem.
> More realistically, can you give me the list of add-ons you have ? The simplest explanation would be that an add-on change the scheduling option.
> I count cards seen today by doing "next due date-interval". But if some add-on change the due date, then this count become false

But the old (dois dias atras) version works. But answering, yes. use or load balancer scheduler.

**Comment by cjdduarte** [comment]
> The wrong numbers are really close of "AprHoje". Can you tell me what AprHoje means ?

`"name": "learning now"`

It's this column

**Comment by Arthur-Milchior** [comment]
Load balancer scheduler keep the above-mentionned property for ivl and date, so it does not seems to be the problem.

**Comment by cjdduarte** [comment]
Did you change anything? An update has gone out and now the number is OK.

**Comment by cjdduarte** [comment]
Well, now it's validated.

**Comment by Arthur-Milchior** [comment]
Yes, I changed thing. As you can see above, a commit is called "Hopefully correcting #43".
