### ISSUE TITLE
Simplify the learning column (eliminate parenthesis)

### ISSUE THREAD

**Issue by ankiuser1995** [Arthur-Milchior/anki-enhance-main-window#46]
Is there a way to edit the configuration in the learning column such that it ONLY displays the learning cards due today - rather than including the parenthesis and the respective information?

**Comment by Arthur-Milchior** [comment]
You can use the name "learning today sum" in a column. You'll have number of cards in learning today (not the number of repetition)

**Comment by ankiuser1995** [comment]
I couldn't find a Learning Today Sum option in the code.

If this isn't possible, would it be possible to combine the learning and
reviews under the DUE column - without including the new cards (like the
way Anki normally does it).  I would really like to use this feature in
regular Anki, however I really really value the feature on this addon that
allows me to remove the cap (1000+, instead of the actual number.)

I really appreciate you getting back to me so soon, thank you for your time!

**Comment by cjdduarte** [comment]
I use a different setting. 
See if that's what you want.

[meta.zip](https://github.com/Arthur-Milchior/anki-enhance-main-window/files/2897124/meta.zip)

**Comment by Arthur-Milchior** [comment]
This column is now added in the column list.
