### ISSUE TITLE
Unseen notes (not cards) column

### ISSUE THREAD

**Issue by BaekToDaFuture** [Arthur-Milchior/anki-enhance-main-window#47]
Sometimes I add new notes to decks that is not finished. So they get put away in the very back (because I do them in order created), and while I take my time to finish a deck, I  always end up forgetting about it (and the information as well). I think it would be nice, if there was an column option to see unseen cards/unseen  notes, like the total card/note column. What do you  think? 

Thank you.
forgive me if there is a way to do this already, I did look several times

**Comment by Arthur-Milchior** [comment]
What do you wall an unseen note ?

I'm pretty sure I already asked this somewhere

**Comment by BaekToDaFuture** [comment]
ok. i look.
