### ISSUE TITLE
suggestion : Cards planned for the next day

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#49]
I would like to have a column that shows how many cards are planned for the next day.

The same that appears in the statistics, but as a column.
![image](https://user-images.githubusercontent.com/42243532/53290347-59e50180-3781-11e9-9cf1-4f06f613e762.png)

**Comment by Arthur-Milchior** [comment]
Would make sens. I'll do it when I go back to this add-on

**Comment by Arthur-Milchior** [comment]
Done

**Comment by dsc321123** [comment]
This is awesome. Thank you for adding this feature.
