### ISSUE TITLE
Help: My window goes blank with anki-enhance-main-window

### ISSUE THREAD

**Issue by pfpr56** [Arthur-Milchior/anki-enhance-main-window#50]
I began using this anki add-on today and it was working very well for a few hours. Eventually though, my anki main window went completely blank. The program did not crash or freeze. All the buttons at the top and on the bottom of the window were still working but all my decks went missing on the main window. I could only access them thru "browse" or Tools -> study deck.

**Comment by aleksejrs** [comment]
You can remove the add-on (`Enhance_main_window.py*` files) from the [Anki2/addons directory](https://apps.ankiweb.net/docs/manual.html#file-locations).

**Comment by Arthur-Milchior** [comment]
You are the second one to report this bug. I must admit I'm really surprised.
Can you may be share your collection. And your list of add-on Because I actually don't understand how it's possible.

**Comment by pfpr56** [comment]
Sorry it took me a while to get back to you. The Add-on suddenly began to work again yesterday. So, just to answer your question, the add-ons I was running (still am) concurrently are "large and colorful buttons" and "True Retention." I included a screen shot with my collection. Hope this helps.

![Screenshot (7)](https://user-images.githubusercontent.com/48114253/54464896-a26f5980-4746-11e9-9f7c-75ca269fa1be.png)

**Comment by Arthur-Milchior** [comment]
It does not help, sorry.
Especially since I don't know those add-ons, so I'd have to take a look at them to see how they interfere
But honestly, if it works, I won't investigate right now. I'll wait until the bug occurs again to anybody.

It's the first-time I see a self-resolving bug. That's strange

**Comment by Arthur-Milchior** [comment]
Out of curiosity, did you update your add-on yesterday ? Because I recently uploaded a change to this add-on. It was adding a new column, (how many review you'll have tomorrow). But it seems to be unrelated to your problem

**Comment by pfpr56** [comment]
I did do some updates but the add-on had already started working again prior to that.

**Comment by Arthur-Milchior** [comment]
until the problem reapper, I'll consider the bug to be closed.

**Comment by feldspar9** [comment]
I am having this same issue.
Please let me know if you need any more information.

**Comment by Arthur-Milchior** [comment]
Sadly, some other users had the same problem and I still have no idea what to do about it :s

**Comment by feldspar9** [comment]
That's okay! If there's any kind of info any of us can give you to help you replicate the issue please let us know!

**Comment by feldspar9** [comment]
It started working today again randomly.
Don't know why.
Only thing I noticed is I went to addons and check for updates and it updates the 3 Hoochie addons (mama, papa, baby) and restarted.

I don't know if there is any connection between that and it now working.
