### ISSUE TITLE
How to have the Zero's show up

### ISSUE THREAD

**Issue by dsc321123** [Arthur-Milchior/anki-enhance-main-window#51]
What would you need to change in the code to get the zero's to show up if nothing is due? Right now, if there is nothing due, the cell will just be blank. Thanks.

**Comment by Arthur-Milchior** [comment]
Right now, it's not possible to do that.
I keep the issue open so I'll know to add it later

**Comment by dsc321123** [comment]
Thanks

**Comment by Arthur-Milchior** [comment]
You can now change the configuration to have the zero. Change the value of "color zero" to the name of the color you want. or to null if you wan it to have the same colour that any other number in the same column

**Comment by dsc321123** [comment]
Awesome. Thank you!

**Comment by Arthur-Milchior** [comment]
You are welcome.
Note that it's not yet on ankiweb. I'll upload when I've dealt with other bug/request

**Comment by dsc321123** [comment]
I'm not sure if this new error I am getting is in reference to #51 or #49.

When I try to expand a deck to view subdecks I get the following:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.10 (22d6feed) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 27, in cmd
  File "aqt\webview.py", line 85, in _onCmd
  File "aqt\webview.py", line 360, in _onBridgeCmd
  File "aqt\deckbrowser.py", line 63, in _linkHandler
  File "aqt\deckbrowser.py", line 242, in _collapse
  File "C:\Users\Douglas\AppData\Roaming\Anki2\addons21\Enhance-Main-Window-Version2\changeFunction.py", line 29, in collapse
    self.save(deck, mainChange = False)#This is the only line of difference
<class 'TypeError'>: save() got an unexpected keyword argument 'mainChange'

**Comment by Arthur-Milchior** [comment]
It should be repaired. Honestly, I don't even understand why this occured in the first place.
