### ISSUE TITLE
Flagged (Red Flag)

### ISSUE THREAD

**Issue by grPici** [Arthur-Milchior/anki-enhance-main-window#55]
Please, add a column for "Flagged".

**Comment by Arthur-Milchior** [comment]
I'll take a look. I've never used a flag before so I don't know how easy it'll be

**Comment by grPici** [comment]
Re: [Arthur-Milchior/anki-enhance-main-window] Flagged (Red Flag) (#55)



Hello,

Great! Thank you. I think Flag is better than Mark. Flags can "mark" individual cards, while Mark is for notes only.

-- 
Regards,
Üdv,
 grPici                            mailto:grofpici@freemail.hu

Monday, May 20, 2019, 7:13:41 PM, you wrote:
2019. május 20., 19:13:41, írtad:





I'll take a look. I've never used a flag before so I don't know how easy it'll be

**Comment by Arthur-Milchior** [comment]
I have taken a look at it. I believe it won't be hard to do it. I just don't have the time right now. But it'll be done

**Comment by Arthur-Milchior** [comment]
Today's commit added what you just asked for.

**Comment by grPici** [comment]
Fine work. Thanks.
