### ISSUE TITLE
mouse icon

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#6]
Could you change the mouse icon to a pointer? Or make parameterizable?
I feel this is not an application pattern when clicking something has an effect.
In your old code I was able to change that. In the new code, no.

![image](https://user-images.githubusercontent.com/42243532/45915524-ad4ad080-be2c-11e8-80af-8d9eceaf6e54.png)

**Comment by Arthur-Milchior** [comment]
Can you please tell me how you did change it into the old code ? I hope it'll help me to change it in the current code

**Comment by cjdduarte** [comment]
before:
```
        <td class=decktd colspan=5>{"&nbsp;"*6*depth}{collapse}<a class="deck{extraclass}" onclick="pycmd('open:{did}')">"""
        # buf+=f"""debug<font style='{cssStyle}' class='tooltip'>{node.name}<span class='tooltiptext'>{self.objectDescription()}</span></font>"""
        buf+=f"""<font style='{cssStyle}'>{node.name}</font>"""
        buf+="""</a></td>"""
```

Now

```
        <td class=decktd colspan=5>{"&nbsp;"*6*depth}{collapse}<a class="deck{extraclass}" onclick="pycmd('open:{did}')">"""
        # buf+=f"""debug<font style='{cssStyle}' class='tooltip'>{node.name}<span class='tooltiptext'>{self.objectDescription()}</span></font>"""
        buf+=f"""<font style='{cssStyle}' class='tooltip'>{node.name}</font>"""
        buf+="""</a></td>"""
```

and had added that line in his css

```
        .tooltip:hover{
         cursor: pointer;
        }
```

**Comment by Arthur-Milchior** [comment]
Corrected, using 
a:hover{
         cursor: pointer;
        }

I'm really surprised that using .tooltip solved anything for you; tooltips are the box which appear when the mouse is over a number. It should be unrelated to links

**Comment by cjdduarte** [comment]
I realized that today too. (I.e.
It worked.
