### ISSUE TITLE
Blank main screen with a particular anki deck

### ISSUE THREAD

**Issue by tigecyclindamycin** [Arthur-Milchior/anki-enhance-main-window#69]
Blank main screen with a particular anki deck

Importing the Lightyear anki deck is successful, and the cards card be seen in the browser, but somehow the main screen is always blank.

Switching on night mode will cause just the menu bar to turn dark with the exception of the main screen, which will remain white.

Switching from browser/study page back to main screen will cause the program to hang.

Toggling off the enhance main window will fix the blank screen issue.

**Comment by Arthur-Milchior** [comment]
Can you give a link to the deck so I can test ?

Do you mean anki dark mode, or the add-on dark mode ?

May be screen shot would help to to understand.

**Comment by tigecyclindamycin** [comment]
I can't attach the decks here. Here's a link you can download from. http://passdropit.com/2gG86b4K

The problem exist both in normal mode, and with the anki add-on Night Mode enabled.
I've attached screenshots of what it looks like.

<img width="992" alt="Screenshot 2019-10-20 at 4 02 56 PM" src="https://user-images.githubusercontent.com/56771063/67156600-3fd0e280-f353-11e9-8481-f623db2618cb.png">
<img width="992" alt="Screenshot 2019-10-20 at 4 03 22 PM" src="https://user-images.githubusercontent.com/56771063/67156601-40697900-f353-11e9-9c50-da9b1a5d590e.png">

Thank you for troubleshooting this issue!

**Comment by tigecyclindamycin** [comment]
edit: it's probably another addon interfering with this. https://ankiweb.net/shared/info/564851917
It converts tags to decks and subsequently causes the screen display to go wonky when used in conjunction with enhance main browser addon.

Using converting the decks back to tags fixes this issue.

**Comment by lovac42** [comment]
This is not an issue with addon interference. The current version of EMW doesn't work with too many decks, this is an issue with the toolkit Anki uses and has been described in detail here: https://github.com/Arthur-Milchior/anki-enhance-main-window/issues/56

**Comment by tigecyclindamycin** [comment]
Ah I see, so as long as I'm not using too many decks, there won't be a problem.

Thank you for taking the time to troubleshoot!
