### ISSUE TITLE
(gray tone) of which deck is selected no longer appears

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#7]
No longer appears (grayscale) of which deck is currently selected

![image](https://user-images.githubusercontent.com/42243532/45915760-13d1ed80-be31-11e8-8896-acdb31a0dff4.png)

**Comment by Arthur-Milchior** [comment]
Thank you, I'll take a look

**Comment by Arthur-Milchior** [comment]
Solved. I'll upload the code when the other bugs you mentionned will be corrected

**Comment by cjdduarte** [comment]
OK

**Comment by cjdduarte** [comment]
It worked.
