### ISSUE TITLE
BUG: Addon won't load since downloading update today

### ISSUE THREAD

**Issue by Krakyn** [Arthur-Milchior/anki-enhance-main-window#71]
Anki notified me that an update for the addon was avaliable, so I downloaded it.

Since downloading, the addon fails to load, and I get this message:

![image](https://user-images.githubusercontent.com/54581534/67630136-c6973980-f8d6-11e9-9e20-40b757f772e4.png)

**Comment by Arthur-Milchior** [comment]
Thank you for noticing it so quickly. Corrected.

**Comment by Krakyn** [comment]
I can confirm this is now fixed. Likewise, thanks for fixing it so quickly! Cheers.
