### ISSUE TITLE
"cards seen today" column causes anki to fail to open without holding shift

### ISSUE THREAD

**Issue by yahmanz** [Arthur-Milchior/anki-enhance-main-window#72]
"name": "cards seen today",
"present": false,

If I set "present" to true, then basically I can't use anki without opening it with addons disabled (holding shift). With no other changes to the addon, my app crashes. I don't need that column to work, so no worries. Just figured I'd let you know!

I have 3 saved error codes if those would be helpful, however they were not from the simple situation I just described. I probably actually jacked up the code those other times. However, I had "cards seen today" set to true and it shows up in each error message.

Thanks for the addon! Its super useful!!! Good work.

**Comment by yahmanz** [comment]
I should add I won't check this very often, unfortunately, but I'll check back in 12 hours

**Comment by Arthur-Milchior** [comment]
May I get an email to answer to you then ?
You can also turn on notification, so you get an email when I answer

Can you please post me the error message. It'll certainly help.
I mean, you're the first to write about this error, so I'm surprised, and I doubt I'll find it easily without your help, it does not seems to be common

**Comment by yahmanz** [comment]
First error message (follows) resulted when I tried to change a bunch of headers and set a bunch of the columns "present": true. It was definitely this addon - I narrowed it down, and it was also my most recent addon and also the only addon I've had to mess with the 'code' for to config. (So the only addon I could have messed up). At this point I thought it was me forgetting to put "header" (quotes on a header) but I had forgotten previously and the addon threw an error and told me which line to correct. Anyways, this time it didn't tell me anything was wrong with the code when I closed the config. I closed anki and reopened except it didn't open because I got this error message. I couldn't load/open any backups even dating back to before I installed this addon. Opened anki by holding shift to keep addons off. Reset this addon to default and closed anki. Reopened and everything was fine.
 ![image](https://user-images.githubusercontent.com/57171805/67890764-ef0d7680-fb16-11e9-8577-593d7e598695.png)

**Comment by yahmanz** [comment]
I don't remember the details quite as well because I was more comfortable, but I double checked that I did everything as I was supposed to in HTML and then I got this code. I still thought I was overloading it by changing too many things, cus I knew I hadn't made a mistake.

![image](https://user-images.githubusercontent.com/57171805/67891618-89ba8500-fb18-11e9-9ea7-4d85bb82b943.png)

**Comment by yahmanz** [comment]
Pretty sure I got a bunch more codes between the second code above and the one I have below currently. I thought I was overloading it so I was changing headers and present (to true) slowly piece by piece and then closing and reloading anki. I went through a ton of errors because I was trying to organize what column showed what and then align them on my main window for comparison. I ended up giving up on trying to make most columns "present: true," and went back to default settings to try again. When I got this current (below) error, I had changed the column with the ("name": "today",)'s header to "Due", then I changed the column with the ("name": "cards seen today",)'s "present": false, to "present": true, as well as named this column's header.

![image](https://user-images.githubusercontent.com/57171805/67891855-0ea59e80-fb19-11e9-8035-417395220291.png)

After I got this error, I went back and changed the column "cards seen today" present =false and anki started running fine again.

**Comment by yahmanz** [comment]
Here is my current config which is working perfectly.

{
    "book symbol": "{",
    "cap value": null,
    "color empty": "red",
    "color empty descendant": "green",
    "color zero": false,
    "columns": [
        {
            "absolute": true,
            "color": "gray",
            "description": "Number of reviews you will see today (new, review and learning)",
            "header": "Due",
            "name": "today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "red",
            "description": "Cards you'll see today which are not new",
            "header": "DO NOT TURN ON",
            "name": "cards seen today",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Reviews which will happen later, either because a review happened recently, or because the card has many review left.",
            "header": null,
            "name": "learning later",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Cards in learning which are due now (and in parentheses, the number of reviews which are due later)",
            "header": null,
            "name": "learning all",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "green",
            "description": "Review cards you will see today (and the ones you will not see today)",
            "header": null,
            "name": "review",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Unseen cards you will see today (what Anki calls New cards). Neither buried nor suspended.",
            "header": null,
            "name": "new today",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "Blue",
            "description": "Cards that have never been answered. Neither buried nor suspended.",
            "header": "New",
            "name": "unseen",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "orange",
            "description": "Cards in learning which are due now",
            "header": "Learning Due",
            "name": "learning now",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "green",
            "description": "Review cards which are due today (not counting those in learning)",
            "header": "Young Mature Due",
            "name": "review due",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "green",
            "description": "Review cards you will see today",
            "header": "Review Due",
            "name": "review today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "purple",
            "description": "Reviewed cards which are due tomorrow",
            "header": "Due Tomorrow",
            "name": "due tomorrow",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "blue",
            "description": "Unseen cards you will see today (what Anki calls New cards), followed by the unseen cards that you will not see today. Neither buried nor suspended.",
            "header": "New (+friends)",
            "name": "unseen new",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "description": "Percent bar to do today",
            "header": "Due Breakdown",
            "name": "bar",
            "names": [
                "review today",
                "learning card",
                "new today",
                "reviewed today"
            ],
            "overlay": null,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of times you saw a question from this deck",
            "header": "Total Views",
            "name": "repeated",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "aqua",
            "description": "Number of reviews done today",
            "header": "Views Today",
            "name": "repeated today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "magenta",
            "description": "Number of reviewed cards seen today",
            "header": "Cards Today",
            "name": "reviewed today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "description": "Percent bar showing the decks's repartition",
            "header": "Card Types",
            "name": "bar",
            "names": [
                "mature",
                "young",
                "learning card",
                "unseen",
                "buried",
                "suspended"
            ],
            "overlay": null,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of cards in the deck",
            "header": "Cards",
            "name": "cards",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards with interval less than 3 weeks",
            "header": "Young",
            "name": "young",
            "overlay": null,
            "percent": true,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards with interval at least 3 weeks",
            "header": "Mature",
            "name": "mature",
            "overlay": null,
            "percent": true,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "orange",
            "description": "Cards in learning (either new cards you see again, or cards which you have forgotten recently, assuming those cards didn't graduate)",
            "header": "Learning",
            "name": "learning card",
            "overlay": null,
            "percent": true,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of buried cards (cards you decided not to see today, or you saw a sibling)",
            "header": "Buried",
            "name": "buried",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of suspended cards (cards you will never see unless you unsuspend them in the browser)",
            "header": null,
            "name": "suspended",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of notes in the deck",
            "header": null,
            "name": "notes",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards which are not yet due",
            "header": null,
            "name": "undue",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "purple",
            "description": "Number of notes with a leech card",
            "header": null,
            "name": "leech",
            "overlay": null,
            "percent": true,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of buried cards (cards you decided not to see today)/Number of suspended cards (cards you will never see unless you unsuspend them in the browser)",
            "header": null,
            "name": "buried/suspended",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of cards/notes in the deck",
            "header": null,
            "name": "notes/cards",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "magenta",
            "description": "Number of reviewed cards seen today and number of reviews",
            "header": null,
            "name": "reviewed today/repeated today",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "purple",
            "description": "Number of marked notes",
            "header": null,
            "name": "marked",
            "overlay": null,
            "percent": true,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards with interval at least 3 weeks/less than 3 weeks ",
            "header": null,
            "name": "mature/young",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Flags from 0 to 4",
            "header": "Flags",
            "name": "all flags",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Flags from 1 to 4",
            "header": "Flags",
            "name": "flags",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "Red",
            "description": "Flag 1",
            "header": "Flag 1",
            "name": "flag 1",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        }
    ],
    "default column color": "grey",
    "do color empty": true,
    "do color marked": true,
    "dot in numbers": true,
    "end symbol": ";",
    "ended marked background color": "yellow",
    "given up symbol": "/",
    "marked background color": "powderblue",
    "option": true,
    "pause symbol": "="
}

**Comment by yahmanz** [comment]
I crashed my anki for you :) 

I changed "cards seen today" column to present: true, closed anki, reopened anki, anki didnt open, and I got this error message.

![image](https://user-images.githubusercontent.com/57171805/67893232-d2277200-fb1b-11e9-9edd-8e54c0dca892.png)

I opened anki holding shift and got the addon's config code which caused the current (above) error. The only difference between the config code below and the config code I posted in my above reply is that "cards seen today" present is false above (anki working) and true below (anki not working).

{
    "book symbol": "{",
    "cap value": null,
    "color empty": "red",
    "color empty descendant": "green",
    "color zero": false,
    "columns": [
        {
            "absolute": true,
            "color": "gray",
            "description": "Number of reviews you will see today (new, review and learning)",
            "header": "Due",
            "name": "today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "red",
            "description": "Cards you'll see today which are not new",
            "header": "DO NOT TURN ON",
            "name": "cards seen today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Reviews which will happen later, either because a review happened recently, or because the card has many review left.",
            "header": null,
            "name": "learning later",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Cards in learning which are due now (and in parentheses, the number of reviews which are due later)",
            "header": null,
            "name": "learning all",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "green",
            "description": "Review cards you will see today (and the ones you will not see today)",
            "header": null,
            "name": "review",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Unseen cards you will see today (what Anki calls New cards). Neither buried nor suspended.",
            "header": null,
            "name": "new today",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "Blue",
            "description": "Cards that have never been answered. Neither buried nor suspended.",
            "header": "New",
            "name": "unseen",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "orange",
            "description": "Cards in learning which are due now",
            "header": "Learning Due",
            "name": "learning now",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "green",
            "description": "Review cards which are due today (not counting those in learning)",
            "header": "Young Mature Due",
            "name": "review due",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "green",
            "description": "Review cards you will see today",
            "header": "Review Due",
            "name": "review today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "purple",
            "description": "Reviewed cards which are due tomorrow",
            "header": "Due Tomorrow",
            "name": "due tomorrow",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "blue",
            "description": "Unseen cards you will see today (what Anki calls New cards), followed by the unseen cards that you will not see today. Neither buried nor suspended.",
            "header": "New (+friends)",
            "name": "unseen new",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "description": "Percent bar to do today",
            "header": "Due Breakdown",
            "name": "bar",
            "names": [
                "review today",
                "learning card",
                "new today",
                "reviewed today"
            ],
            "overlay": null,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of times you saw a question from this deck",
            "header": "Total Views",
            "name": "repeated",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "aqua",
            "description": "Number of reviews done today",
            "header": "Views Today",
            "name": "repeated today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "magenta",
            "description": "Number of reviewed cards seen today",
            "header": "Cards Today",
            "name": "reviewed today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "description": "Percent bar showing the decks's repartition",
            "header": "Card Types",
            "name": "bar",
            "names": [
                "mature",
                "young",
                "learning card",
                "unseen",
                "buried",
                "suspended"
            ],
            "overlay": null,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of cards in the deck",
            "header": "Cards",
            "name": "cards",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards with interval less than 3 weeks",
            "header": "Young",
            "name": "young",
            "overlay": null,
            "percent": true,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards with interval at least 3 weeks",
            "header": "Mature",
            "name": "mature",
            "overlay": null,
            "percent": true,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "orange",
            "description": "Cards in learning (either new cards you see again, or cards which you have forgotten recently, assuming those cards didn't graduate)",
            "header": "Learning",
            "name": "learning card",
            "overlay": null,
            "percent": true,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of buried cards (cards you decided not to see today, or you saw a sibling)",
            "header": "Buried",
            "name": "buried",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of suspended cards (cards you will never see unless you unsuspend them in the browser)",
            "header": null,
            "name": "suspended",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of notes in the deck",
            "header": null,
            "name": "notes",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards which are not yet due",
            "header": null,
            "name": "undue",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "purple",
            "description": "Number of notes with a leech card",
            "header": null,
            "name": "leech",
            "overlay": null,
            "percent": true,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of buried cards (cards you decided not to see today)/Number of suspended cards (cards you will never see unless you unsuspend them in the browser)",
            "header": null,
            "name": "buried/suspended",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "black",
            "description": "Number of cards/notes in the deck",
            "header": null,
            "name": "notes/cards",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "magenta",
            "description": "Number of reviewed cards seen today and number of reviews",
            "header": null,
            "name": "reviewed today/repeated today",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "purple",
            "description": "Number of marked notes",
            "header": null,
            "name": "marked",
            "overlay": null,
            "percent": true,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Number of reviewed cards with interval at least 3 weeks/less than 3 weeks ",
            "header": null,
            "name": "mature/young",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Flags from 0 to 4",
            "header": "Flags",
            "name": "all flags",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": null,
            "description": "Flags from 1 to 4",
            "header": "Flags",
            "name": "flags",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        },
        {
            "absolute": true,
            "color": "Red",
            "description": "Flag 1",
            "header": "Flag 1",
            "name": "flag 1",
            "overlay": null,
            "percent": false,
            "present": false,
            "subdeck": true
        }
    ],
    "default column color": "grey",
    "do color empty": true,
    "do color marked": true,
    "dot in numbers": true,
    "end symbol": ";",
    "ended marked background color": "yellow",
    "given up symbol": "/",
    "marked background color": "powderblue",
    "option": true,
    "pause symbol": "="
}

**Comment by yahmanz** [comment]
I feel like I probably gave you too much info/unnecessary info but if it is a lesser experienced problem then I figured I'd give you too much info rather than too little. 

Here are my other addons in case that helps.

![image](https://user-images.githubusercontent.com/57171805/67894099-7e1d8d00-fb1d-11e9-9786-ba76c136406d.png)

Thank you again for your addon! Sorry to find a problem with it (maybe its me idk!) but its working great the way I have it set up.

**Comment by Jefftree** [comment]
Hi @Arthur-Milchior, I was able to reproduce the same problem. Looks like you're missing a column definition key for "cards seen today" when associating the columns to the header/overlay in the dict https://github.com/Arthur-Milchior/anki-enhance-main-window/blob/master/strings.py#L7 and https://github.com/Arthur-Milchior/anki-enhance-main-window/blob/master/strings.py#L57.

**Comment by msnjuegos** [comment]
@Jefftree  Your solution works for me! I changed manually the files of your PR in my addon folder. Thanks a lot.
