### ISSUE TITLE
Study Now on the Main Window

### ISSUE THREAD

**Issue by Doomwhite** [Arthur-Milchior/anki-enhance-main-window#73]
Would it be possible to make the "Study Now" button available on the main window? I'm hiding my "due" cards, but that's meaningless if when I click on the deck it shows me anyway.
https://prnt.sc/ps07ks

**Comment by Arthur-Milchior** [comment]
I'm guessing I could add that as an extra option, indeed. Do you think you'd like to have two buttons, one for study now, and one for due ? Or do you want just to replace the button ?

**Comment by Doomwhite** [comment]
"Do you think you'd like to have two buttons, one for study now, and one for due ?"
That would be amazing.

**Comment by Arthur-Milchior** [comment]
Please use add-on https://ankiweb.net/shared/info/1024346707
I thought it would makes sens to create as a different add-on

**Comment by Doomwhite** [comment]
Ok, ty, it's working.
