### ISSUE TITLE
Can't change text color

### ISSUE THREAD

**Issue by 2pascal** [Arthur-Milchior/anki-enhance-main-window#74]
I'm using the night mode addon, so text under the "New (unseen)" column is black, nearly the same shade as the background. 

For some columns, color can be specified in the config as a hex or text-specified color. Many other colums leave color as "null". If I change it to a text-specified color like green (without quotes), nothing happens, but it appears that format works for columns that had colors assigned already.
I tried using #ffffffand "#ffffff". It either threw an error, and in the case of using quotes around the hex, it simply did nothing, and the text remained black.

Can you please help me figure out how to change the color of the text (the numbers) under the new(unseen column)? I can't clearly see the number of cards in each deck due to night mode use 
and cannot configure a different color using the config or anything else I can find in the code. 

1) How can I fix this?
2) Could an alternative color scheme be implemented which is friendly to both regualr and night mode? (Basically just get rid of black text and replace it with green, blue, aqua, anything. 

Thank you!

**Comment by Arthur-Milchior** [comment]
If you change anything in the config to green without quotes, I'm surprised  that you don't get an error message by the add-on manager. Normally, it should rejects this config as it's badly formatted.
I didn't trying using both this add-on and night mode. Did you check whether you can use it correctly without night mode ?

Did you also try to restart anki ? Or at least leave the deck browser window and come back to it (i.e. reviewing a card and coming back.)

**Comment by 2pascal** [comment]
Okay, it wasn’t working with hex (with or without quotes), but text codes are working with quotes. Thanks.
