### ISSUE TITLE
bug in version 2.1.17

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#77]
Anki 2.1.17 (c69ccb50) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=?

D:\Anki\Anki.2.1.data\addons21\877182321\node.py:387: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if ((not learningNow)) and (self.timeDue[kind] is not 0):

**Comment by Arthur-Milchior** [comment]
Already corrected

**Comment by cjdduarte** [comment]
Tanks
