### ISSUE TITLE
Drag and drop stopped working

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#8]
The drag-and-drop function for creating a hierarchy has stopped working.

**Comment by cjdduarte** [comment]
drag and drop decks.

**Comment by Arthur-Milchior** [comment]
either I corrected this while doing other correction, or I'll need more details. Because, currently, it seems to work fine for me.

Could you please update the add-on, test again, and otherwise tell me more precisely what you tried to do which failed, please ?

**Comment by Arthur-Milchior** [comment]
In fact, I guess I did correct it while I corrected the «grey» of selected decks. I think the same problem was causing both errors.

**Comment by cjdduarte** [comment]
It worked.
