### ISSUE TITLE
Suggestion: Option to not show parent deck info when it's expanded

### ISSUE THREAD

**Issue by StookDog** [Arthur-Milchior/anki-enhance-main-window#81]
I think it would be nice if there was an option to allow parent decks to only show their stats next to them when the deck is collapsed and to show the subdeck information only when they are expanded. I have many decks and when they are all open it's hard to get a feel for what really is due because a lot of the information is repeated. I attached a  picture of what that might look like (sorry for the poor editing). Thanks!

![Enhanced Main Screen Rec](https://user-images.githubusercontent.com/16076019/74594785-e9b53880-4fee-11ea-9c6a-bab58c0b3216.png)

Here's a link if that doesn't work:  https://imgur.com/a/zYjrs7N

**Comment by Arthur-Milchior** [comment]
Hi

I assume you are the one who made a similar comment on ankiweb. If so, thanks for reading my answer and posting here

**Comment by Arthur-Milchior** [comment]
I can certainly do it, this makes a lot of sens.

**Comment by Arthur-Milchior** [comment]
Done
There is a new option "hide values of parent decks when subdecks are shown" if you set it to true, it'll do what you wanted.
It took more than two hour of works, I'd appreciate if you can tip for this code created for your request: https://ko-fi.com/arthurmilchior

**Comment by StookDog** [comment]
Great! Yeah, that was me. I really appreciate your quick response and time put into adding this feature! I'll send a tip for sure.
