### ISSUE TITLE
improvement suggestion

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#9]
Sorry for not knowing how to use "pull requests". I am studying github for collaborative purposes.

Follow suggestions for improvements.
Let me know if you helped so you can close this post.

[877182321.zip](https://github.com/Arthur-Milchior/anki-enhance-main-window/files/2407719/877182321.zip)

One change I did not do since I did not find it in your code is the edge of this gear.
I'm trying to standardize it with the new version 2.1 of Anki which I think is cleaner. What is the line of your code that puts this border?

![image](https://user-images.githubusercontent.com/42243532/45916659-14be4b80-be40-11e8-99ee-3dfcd2b0b88d.png)

**Comment by cjdduarte** [comment]
Will you see anything on this topic or should I close it?

**Comment by Arthur-Milchior** [comment]
I see it, yes.

**Comment by Arthur-Milchior** [comment]
I don't understand, what do you call a border ?

**Comment by Arthur-Milchior** [comment]
Done. Buttons are removed, only gears remain

**Comment by cjdduarte** [comment]
Wonderful.
That's what I was trying to do for two days.
I would only make one change. I would change "center" to "right".

Your code:
```
def gear(did):
    return """<td align=center class=opts><a onclick='pycmd(\"opts:{int(did)}\");'><img src='/_anki/imgs/gears.svg' class=gears></a></td>"""
```

My change
```
def gear(did):
    return """<td align=right class=opts><a onclick='pycmd(\"opts:{int(did)}\");'><img src='/_anki/imgs/gears.svg' class=gears></a></td>"""
```
But that was it. It is perfect

**Comment by cjdduarte** [comment]
Its OK
