### ISSUE TITLE
issue with enhance main window 

### ISSUE THREAD

**Issue by ellmoore** [Arthur-Milchior/anki-enhance-main-window#92]
hello, I hope you're well. 

I downloaded Anki today and was advised to have this add on, however when I tried to install it I came up with this pop up; 
877182321: Invalid code, or add-on not available for your version of Anki. I currently have 2.1.30 version. 

I hope you can help! your add on would be very useful with my studies 

Many thanks,

**Comment by Arthur-Milchior** [comment]
Same issue as https://github.com/Arthur-Milchior/anki-enhance-main-window/issues/90 
I still have not enough time and motivation for this big add-on
