### ISSUE TITLE
Compatibility with Anki 2.1.32

### ISSUE THREAD

**Issue by DannyWilliamsDJW** [Arthur-Milchior/anki-enhance-main-window#95]
Hi there,
I can't get this add-on with the latest version of Anki

Please may you update it and let me know when you've done it!

I'll leave a very positive feedback!

Thanks

Danny

**Comment by Arthur-Milchior** [comment]
Duplicate of https://github.com/Arthur-Milchior/anki-enhance-main-window/issues/90
